package com.career.analyzer.service;

import com.itextpdf.text.*;
import com.itextpdf.text.pdf.*;
import org.springframework.stereotype.Service;

import java.io.ByteArrayOutputStream;
import java.time.LocalDate;

@Service
public class PDFReportService {

    public byte[] generateReport(
            String skills,
            String careerGoal,
            String interestedDomain,
            String education,
            String experienceLevel) {

        try {

            ByteArrayOutputStream baos =
                    new ByteArrayOutputStream();

            Document document =
                    new Document(PageSize.A4);

            PdfWriter.getInstance(
                    document,
                    baos);

            document.open();

            Font titleFont =
                    new Font(
                            Font.FontFamily.HELVETICA,
                            20,
                            Font.BOLD);

            Font headingFont =
                    new Font(
                            Font.FontFamily.HELVETICA,
                            14,
                            Font.BOLD);

            Font normalFont =
                    new Font(
                            Font.FontFamily.HELVETICA,
                            11);

            // TITLE
            Paragraph title =
                    new Paragraph(
                            "CAREER ANALYZER REPORT",
                            titleFont);

            title.setAlignment(
                    Element.ALIGN_CENTER);

            document.add(title);
            document.add(new Paragraph(" "));

            // SUMMARY TABLE
            document.add(
                    new Paragraph(
                            "Candidate Summary",
                            headingFont));

            PdfPTable table =
                    new PdfPTable(2);

            table.setWidthPercentage(100);

            table.addCell("Education");
            table.addCell(
                    education == null ?
                            "-" : education);

            table.addCell("Experience");
            table.addCell(
                    experienceLevel == null ?
                            "-" : experienceLevel);

            table.addCell("Interested Domain");
            table.addCell(
                    interestedDomain == null ?
                            "-" : interestedDomain);



            table.addCell("Career Goal");
            table.addCell(
                    careerGoal == null ?
                            "-" : careerGoal);

            document.add(table);

            document.add(new Paragraph(" "));

            // SKILLS
            document.add(
                    new Paragraph(
                            "Detected Skills",
                            headingFont));

            document.add(
                    new Paragraph(
                            skills == null ?
                                    "-" : skills,
                            normalFont));

            document.add(new Paragraph(" "));

            // RESUME STRENGTH
            int count = 0;

            if(skills != null &&
                    !skills.isBlank()) {

                count =
                        skills.split(",").length;
            }

            int strength =
                    Math.min(
                            count * 10,
                            100);

            document.add(
                    new Paragraph(
                            "Resume Strength : "
                                    + strength + "%",
                            headingFont));

            document.add(new Paragraph(" "));

            // DATE
            document.add(
                    new Paragraph(
                            "Generated On : "
                                    + LocalDate.now(),
                            normalFont));

            document.add(new Paragraph(" "));

            // FOOTER
            Paragraph footer =
                    new Paragraph(
                            "Generated by Career Analyzer",
                            normalFont);

            footer.setAlignment(
                    Element.ALIGN_CENTER);

            document.add(footer);

            document.close();

            return baos.toByteArray();

        } catch (Exception e) {

            throw new RuntimeException(
                    "PDF Generation Failed",
                    e);
        }
    }

}
