document.addEventListener("DOMContentLoaded", initializeReport);

// -------------------------------
// 1. Initialize Page
// -------------------------------
function initializeReport() {

    const resumeData =
        JSON.parse(localStorage.getItem("resumeData"));

    if (!resumeData) {

        alert("No resume analysis found. Please upload resume first.");

        window.location.href = "upload.html";

        return;
    }

    console.log("Report initialized successfully");
}

// -------------------------------
// 2. Download Report
// -------------------------------
function downloadReport() {

    const resumeData =
        JSON.parse(localStorage.getItem("resumeData"));

    if (!resumeData) {

        alert("No report available. Please upload resume first.");

        return;
    }

    let report = "";

    // ---------------- HEADER ----------------
    report += "=====================================\n";
    report += "      CAREER ANALYZER REPORT\n";
    report += "=====================================\n\n";

    // ---------------- BASIC INFO ----------------
    report += "File Name : " + (resumeData.fileName || "N/A") + "\n";
    report += "File Type : " + (resumeData.fileType || "N/A") + "\n";
    report += "Domain    : " + (resumeData.domain || "N/A") + "\n\n";

    // ---------------- DETECTED SKILLS ----------------
    report += "========== DETECTED SKILLS ==========\n";

    const categorized = resumeData.categorizedSkills || {};

    if (Object.keys(categorized).length === 0) {
        report += "No skills detected\n";
    } else {

        for (const category in categorized) {

            report += "\n" + category + "\n";

            (categorized[category] || []).forEach(skill => {
                report += "  • " + skill + "\n";
            });
        }
    }

    report += "\n";

    // ---------------- MISSING SKILLS ----------------
    report += "========== MISSING SKILLS ==========\n";

    const missingSkills = resumeData.missingSkills || [];

    if (missingSkills.length === 0) {
        report += "No Missing Skills\n";
    } else {

        missingSkills.forEach(skill => {
            report += "• " + skill + "\n";
        });
    }

    report += "\n";

    // ---------------- CAREER RECOMMENDATIONS ----------------
    report += "========== CAREER RECOMMENDATIONS ==========\n";

    const recommendations = resumeData.recommendations || [];

    if (recommendations.length === 0) {
        report += "No recommendations available\n";
    } else {

        recommendations.forEach(job => {

            report +=
                (job.role || "Unknown Role") +
                " : " +
                (job.score !== undefined? Number(job.score).toFixed(2): "0.00") +
                "% Match\n";
        });
    }

    report += "\n";

    // ---------------- ROADMAP ----------------
    report += "========== LEARNING ROADMAP ==========\n";

    const roadmap = resumeData.roadmapSteps || [];

    if (roadmap.length === 0) {
        report += "No roadmap available\n";
    } else {

        roadmap.forEach((step, index) => {

            report += (index + 1) + ". " + step + "\n";
        });
    }

    // ---------------- FOOTER ----------------
    report += "\n=====================================\n";
    report += "Generated by Career Analyzer\n";
    report += "=====================================";

    // ---------------- DOWNLOAD FILE ----------------
    const blob = new Blob([report], { type: "text/plain" });

    const url = URL.createObjectURL(blob);

    const a = document.createElement("a");

    a.href = url;
    a.download ="Career_Report_" +
    new Date().toISOString().split("T")[0] +
    ".txt";

    document.body.appendChild(a);
    a.click();

    document.body.removeChild(a);

    URL.revokeObjectURL(url);
}

// -------------------------------
// 3. Theme Toggle
// -------------------------------
function toggleTheme() {

    document.body.classList.toggle("dark-mode");

    const isDark =
        document.body.classList.contains("dark-mode");

    localStorage.setItem(
        "theme",
        isDark ? "dark" : "light"
    );
}

// -------------------------------
// 4. Restore Theme on Load
// -------------------------------
(function initTheme() {

    const theme = localStorage.getItem("theme");

    if (theme === "dark") {

        document.body.classList.add("dark-mode");
    }
})();